export const CHANGE_FILTER = 'CHANGE_FILTER';
export const CHANGE_TOPIC = 'CHANGE_TOPIC';
export const CHANGE_QUESTION = 'CHANGE_QUESTION';
export const REQUEST_DATA = 'REQUEST_DATA';
export const RECEIVE_DATA = 'RECEIVE_DATA';
export const SET_TOOLTIP = 'SET_TOOLTIP';